apiVersion: v2
name: formance_dst
version: 1.0.0
dependencies:
  - name: regions
    repository: oci://ghcr.io/formancehq/helm
    version: 3.7.2
  - name: strimzi-kafka-operator
    repository: oci://quay.io/strimzi-helm
    version: 0.50.0
