build-manifest output workload_tag='daily':
	rm -f -- '{{output}}'
	helm dependency update
	helm dependency build
	helm template . --set "ledger.previous_tag=$LEDGER_PREVIOUS_TAG" --set "workload.tag={{workload_tag}}" >> '{{output}}'

push faults='true':
	#!/usr/bin/env bash

	set -euxo pipefail
	tmpdir=$(mktemp -d)
	trap 'rm -rf $tmpdir' EXIT

	[ "{{faults}}" = 'true' ] && tag=daily_faults || tag=daily_nofaults

	just build-manifest "$tmpdir/resources.yaml" "$tag"

	docker build -f Dockerfile.config -t "$ANTITHESIS_REPOSITORY/antithesis-config:$tag" $tmpdir
	docker push "$ANTITHESIS_REPOSITORY/antithesis-config:$tag"
