build faults='true':
	#!/usr/bin/env bash
	[ "$faults" = 'true' ] && tag=daily_faults || tag=daily_nofaults
	[ "$faults" = 'true' ] && faults_mode=faults || faults_mode=nofaults

	docker build --build-arg LEDGER_LATEST_TAG="$LEDGER_LATEST_TAG" --build-arg FAULTS_MODE="$faults_mode" -f Dockerfile -t "$ANTITHESIS_REPOSITORY/workload:$tag" .

push faults='true':
	#!/usr/bin/env bash

	[ "$faults" = 'true' ] && tag=daily_faults || tag=daily_nofaults
	just build "$tag"
	docker push "$ANTITHESIS_REPOSITORY/workload:$tag"
